#!/usr/bin/env python3
"""Generate an as1600 source dump of a .bin ROM (16-bit big-endian words).

Usage: dump_rom.py ROM.bin BASE_ADDR_HEX OUT.asm [PATCHES.py] [--stop HEX]

PATCHES.py, when given, is a Python literal dict mapping word address (int) to
an as1600 expression string that replaces the original word at that address.
The original value is kept in a comment so every patch site stays auditable.
The expressions are expected to be symbols defined by the including source
(patches.asm); building with those symbols set to the original values must
reproduce the original ROM byte-for-byte (the `make verify-org` guard).

--stop HEX truncates the dump so it stops BEFORE that word address (exclusive
upper bound). Only needed when a hook segment's own ORG takes over part of
the cart's original image span -- Shark Shark is the first cart in this
family where the original ROM already occupies the whole page (through
$67F9) that every prior port's netcode ORG'd into, so the patched dump stops
at $67FA and hook.asm resumes at $6800. `verify-org`'s unpatched dump never
passes --stop; it must always reproduce the full original ROM.
"""
import ast
import sys


def main():
    argv = list(sys.argv[1:])
    stop = None
    if "--stop" in argv:
        i = argv.index("--stop")
        stop = int(argv[i + 1], 16)
        del argv[i:i + 2]

    rom_path, base_hex, out_path = argv[0], argv[1], argv[2]
    base = int(base_hex, 16)
    patches = {}
    if len(argv) > 3:
        with open(argv[3]) as f:
            patches = ast.literal_eval(f.read())

    data = open(rom_path, "rb").read()
    assert len(data) % 2 == 0, "odd byte count"
    words = [(data[i] << 8) | data[i + 1] for i in range(0, len(data), 2)]
    if stop is not None:
        assert base <= stop <= base + len(words), \
            f"--stop ${stop:04X} outside ROM (${base:04X}-${base + len(words) - 1:04X})"
        words = words[:stop - base]

    unused = set(patches) - set(range(base, base + len(words)))
    assert not unused, f"patch addresses outside ROM: {[hex(a) for a in unused]}"

    with open(out_path, "w") as out:
        out.write(f"; Generated by tools/dump_rom.py from {rom_path} -- DO NOT EDIT\n")
        out.write(f"        ORG     ${base:04X}\n")
        row = []
        for i, w in enumerate(words):
            addr = base + i
            if addr in patches:
                if row:
                    out.write(f"        DECLE   {', '.join(row)}\t; ${addr - len(row):04X}\n")
                    row = []
                out.write(f"        DECLE   {patches[addr]}\t; ${addr:04X} PATCH (orig ${w:04X})\n")
            else:
                row.append(f"${w:04X}")
                if len(row) == 8:
                    out.write(f"        DECLE   {', '.join(row)}\t; ${addr - 7:04X}\n")
                    row = []
        if row:
            out.write(f"        DECLE   {', '.join(row)}\t; ${base + len(words) - len(row):04X}\n")


if __name__ == "__main__":
    main()
