#!/usr/bin/env python3
"""Convert a record-build debugger session log (containing `m 9000 C00` and
`m 8100 20` dumps) into src/replay_data.asm for a SPIKE_REPLAY build.

Frog Bog's REC_CAPTURE (src/vdispatch.asm) logs 4 words/tick at $9000 + T*4:
[L decoded, R decoded, L keypad, R keypad] -- unlike sibling ports' disc-only
2-word format, Frog Bog's day/night and skill-level selection go through
keypad dispatch too, so the keypad pair must be replayed as well or a
recorded session can't reproduce the mode the player actually selected.
VIRT_CAPTURE's SPIKE_REPLAY branch reads this same 4-word layout and needs
REPLAY_LEN defined alongside REPLAY_TBL.

Usage: mk_replay.py session.log > src/replay_data.asm
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from crc_trace_diff import parse  # noqa: E402  (same dump format)

REC_CAP = 768  # REC_CAPTURE's own tick cap (src/vdispatch.asm @@rec_done)


def main():
    mem = parse(sys.argv[1])
    ticks = mem.get(0x8108, 0) | (mem.get(0x8109, 0) << 8)
    n = min(ticks, REC_CAP)
    print(f"; Generated by tools/mk_replay.py -- {n} recorded game ticks")
    print(f"REPLAY_LEN      EQU     {n}")
    print("REPLAY_TBL:")
    for t in range(REC_CAP):
        slot = 0x9000 + t * 4
        l_dec = mem.get(slot, 0x40) & 0xFF
        r_dec = mem.get(slot + 1, 0x40) & 0xFF
        l_kp = mem.get(slot + 2, 0x00) & 0xFF
        r_kp = mem.get(slot + 3, 0x00) & 0xFF
        print(f"        DECLE   ${l_dec:02X}, ${r_dec:02X}, "
              f"${l_kp:02X}, ${r_kp:02X}\t; tick {t}")


if __name__ == "__main__":
    main()
